### ISSUE TITLE
Include validation i18n translation file

### ISSUE THREAD

**Issue by baohx2000** [synapsestudios/frontend-template#109]
### Acceptance Criteria
1. Include a separate validations translation i18n file which would be injected into the main i18n json blob to utilize new constant-y errors.

### Tasks
- None

### Additional Notes
- Relates to synapsestudios/synapse-base#202

**Comment by baohx2000** [comment]
:arrow_double_down: :sunny:

**Comment by zpchavez** [comment]
:o:

**Comment by zpchavez** [comment]
:o:

**Comment by kylecesmat** [comment]
:boom: we removed intl
