### ISSUE TITLE
User store incomplete

### ISSUE THREAD

**Issue by nearengine** [synapsestudios/frontend-template#115]
## Description

Not sure if this *really* counts as a bug, but the user store serializes a value that doesn't exist (`this.pending`), and the store doesn't implement the `LOGGING_IN` action. This stuff could be cleaned up a little. Also it doesn't meet our alignment guidelines.

Also, the auth action should not use `.fail()` to resolve failed promises.

**Comment by baohx2000** [comment]
I think user stuff should be split into a separate repo/npm-module.  Some projects we do have no concept of users, so the code is unnecessary for the template.  Splitting it out would allow us to more easily upgrade when needed without having to copy-paste or cherry pick.

**Comment by nearengine** [comment]
I like that idea. I'd be good with that.

**Comment by paulstatezny** [comment]
@baohx2000 I think that's why it's in synapsestudios/frontend-template instead of synapsestudios/synapse-common -- it can be yanked out of a project pretty easily for the 20% of projects that don't have users.

**Comment by bobeagan** [comment]
I'd rather the frontend template be just a template for directory structure and webpack-ery.  If we wanted to improve upon the user-based features we can more easily do that if they are a separate module.

**Comment by paulstatezny** [comment]
:arrow_down: :sunny:

**Comment by kylecesmat** [comment]
:boom: we've decided to keep the frontend mostly clean of bootstrap code
