### ISSUE TITLE
react-intl 1.x doesn't work with react .14

### ISSUE THREAD

**Issue by agerbens** [synapsestudios/frontend-template#154]
react-intl 1.x works up to React 0.13.3.

If you try to use it with .14, you get the error 
```
A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

react-intl 2.0 will work with react 14, but it's still in beta stages.

**Comment by chrisheninger** [comment]
2.0.0 moved from beta to release candidate a couple of days ago and it will support both v14 and v15.

https://github.com/yahoo/react-intl/releases

**Comment by nearengine** [comment]
A couple projects after adding intl I'm not sure it's something that should be included in frontend template... anyone have any compelling reasons to leave it in? I don't think most projects end up requiring actual internationalization.

**Comment by nearengine** [comment]
Aaaaand it's gone
