### ISSUE TITLE
Implement gulp distribution script

### ISSUE THREAD

**Issue by areida** [synapsestudios/frontend-template#58]
### Acceptance Criteria
1. `gulp dist` builds and zips the application
1. `gulp clean:dist` empties the `/dist` directory
1. `gulp clean` cleans the `/dist` directory
1. Add `dist` to `.gitignore`

### Tasks
- Add gulp-zip to packages.json
- Update gulpfile
    - Add 'dist' gulp task
    - Add 'clean:dist' gulp task

```javascript
var zip = require('gulp-zip');

gulp.task('dist', ['build'], function() {
    return gulp.src('./build/**/*', {dot : true})
        .pipe(zip('frontend-' + Date.now() + '.zip'))
        .pipe(gulp.dest('./dist'));
});

gulp.task('clean', ['clean:app', 'clean:dist', 'clean:test']);

gulp.task('clean:dist', function(cb) {
    rimraf('./dist', cb);
});
```

### Notes
- The gulpfile on synapsestudios/pat.usmexpat.com has this implemented
- gulp-zip should be @2.0.1 or newer

**Comment by canfie1d** [comment]
:boom: Gulp is dead.
