### ISSUE TITLE
remove user logged in and out from template

### ISSUE THREAD

**Issue by canfie1d** [synapsestudios/frontend-template#61]
### Acceptance Criteria
1. user logged in and user logged out removed from template
1. user logged in and user logged out added to examples

### Tasks
1. remove user-logged-in.jsx and user-logged-out.jsx from template
1. include in an examples folder to be drawn from and expanded upon.

**Comment by kylecesmat** [comment]
will be removed in #91

**Comment by kylecesmat** [comment]
:boom: done in #123
