### ISSUE TITLE
Change `test-helpers` directory to `test-helper`

### ISSUE THREAD

**Issue by paulstatezny** [synapsestudios/frontend-template#67]
### Acceptance Criteria
1. Tests run without a hitch.

### Tasks
- Change directory and all references to it.

### Additional Notes
- synapsestudios/synapse-base has a `TestHelper` namespace. By making them the same, it will be less confusing and easier to remember.

**Comment by paulstatezny** [comment]
:one: :sunny: :arrow_down:

**Comment by bobeagan** [comment]
:o:

**Comment by nearengine** [comment]
No one actually cares, maybe this can be done in #143

**Comment by paulstatezny** [comment]
> No one actually cares

Ooo, arrow in the :heart: @nearengine ;-)

**Comment by nearengine** [comment]
We unfortunately rewrite the testing framework more than we write tests :/
