### ISSUE TITLE
Watchify breaks gulp watch

### ISSUE THREAD

**Issue by nearengine** [synapsestudios/frontend-template#72]
## Description
Seems to be an issue with the older version of watchify - works fine with 2.3.0. Get the following error on a gulp watch:

```events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOTDIR, lstat '/Users/synapse/Desktop/researchaz.org/node_modules/react/react.js/package.json'
```

If we implement #69 this won't matter, but existing gulp projects will need to be updated.

**Comment by paulstatezny** [comment]
:boom: Merged #69
