### ISSUE TITLE
Update SASS-Loader for Node v.12

### ISSUE THREAD

**Issue by kylecesmat** [synapsestudios/frontend-template#73]
## Description
* We're requiring the current stable version of SASS Loader (0.3.1), which requires an outdated version of node-sass

* SASS Loader 0.4.0-beta.1 works because it requires the latest node-sass, which is compatible with Node v.12

**Comment by paulstatezny** [comment]
I approve this usage of a beta tool :-P

**Comment by kylecesmat** [comment]
:boom: this was merged in #71
